name: enie_production
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.1+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image: ^3.0.2
  # provider: ^5.0.0
  google_nav_bar: ^5.0.3
  line_icons: ^2.0.1
  hexcolor: ^2.0.5
  font_awesome_flutter: ^8.12.0
  http: ^0.13.0
  rxdart: ^0.23.1
  get: ^3.15.0
  flutter_staggered_grid_view: ^0.3.2
  convert: ^3.0.0
  carousel_pro: ^1.0.0
  dio: ^4.0.0
  shared_preferences: ^2.0.7
  flushbar: ^1.10.4
  cupertino_icons: ^1.0.2
  google_fonts: ^2.0.0
  get_it: ^5.0.3
  chopper: ^3.0.2
  json_annotation: 3.1.1
  overlay_support: ^1.2.1
  image_picker: ^0.7.5+2
  flutter_bloc: ^7.0.0
  mime: ^1.0.0
  open_file: ^3.2.1
  flutter_chat_ui: ^1.2.0
  uuid: ^3.0.4
  dependencies:
  intl: ^0.17.0
  file_picker: ^4.0.0

  # chopper_generator: ^3.0.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.1
  json_serializable: 3.5.1
  chopper_generator: ^3.0.0

flutter:
  uses-material-design: true
  assets:
   
    - messages.json

  